export const USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const BAD_CREDENTIALS = 'BAD_CREDENTIALS';
